#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_vision.VisionStarter import VisionStarter

plugin = 'provider_kill_mission.ProviderKillMission.ProviderKillMission'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
