name: Docker Image CI

on:
  push:
    branches: [feature/**]

jobs:
  build:
    name: "Build docker image"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:${GITHUB_REF##*/}  --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VERSION=${GITHUB_REF##*/}-${BUILD_DATE}
        env:
          IMAGE_NAME: provider_kill_mission
          BUILD_DATE:
